
-- Script DML: Inserção de Dados

-- Dados para a tabela CLIENTES
INSERT INTO USR_GESTAO_HOTEL.CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE) VALUES (1, 'João Silva', 'joao.silva@email.com', '123456789');
INSERT INTO USR_GESTAO_HOTEL.CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE) VALUES (2, 'Maria Oliveira', 'maria.oliveira@email.com', '987654321');

-- Dados para a tabela QUARTOS
INSERT INTO USR_GESTAO_HOTEL.QUARTOS (QUARTO_ID, NUMERO, TIPO, PRECO_DIARIA) VALUES (1, '101', 'Standard', 150.00);
INSERT INTO USR_GESTAO_HOTEL.QUARTOS (QUARTO_ID, NUMERO, TIPO, PRECO_DIARIA) VALUES (2, '102', 'Suíte', 300.00);

-- Dados para a tabela RESERVAS
INSERT INTO USR_GESTAO_HOTEL.RESERVAS (RESERVA_ID, CLIENTE_ID, QUARTO_ID, DATA_CHECKIN, DATA_CHECKOUT, STATUS) 
VALUES (1, 1, 1, TO_DATE('2024-12-15', 'YYYY-MM-DD'), TO_DATE('2024-12-20', 'YYYY-MM-DD'), 'Confirmada');

-- Dados para a tabela PEDIDOS
INSERT INTO USR_GESTAO_HOTEL.PEDIDOS (PEDIDO_ID, CLIENTE_ID, DATA_PEDIDO, TOTAL, STATUS) 
VALUES (1, 1, SYSTIMESTAMP, 45.00, 'Pago');

-- Dados para a tabela ITENS_PEDIDO
INSERT INTO USR_GESTAO_HOTEL.ITENS_PEDIDO (ITEM_PEDIDO_ID, PEDIDO_ID, NOME_ITEM, QUANTIDADE, PRECO_UNITARIO) 
VALUES (1, 1, 'Hambúrguer', 2, 15.00);
INSERT INTO USR_GESTAO_HOTEL.ITENS_PEDIDO (ITEM_PEDIDO_ID, PEDIDO_ID, NOME_ITEM, QUANTIDADE, PRECO_UNITARIO) 
VALUES (2, 1, 'Refrigerante', 2, 7.50);
