CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CAMPANHAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INTERACOES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESTUDANTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROFESSORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CURSOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISCIPLINAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MATRICULAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FUNCIONARIOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROJETOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TAREFAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VEICULOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VIAGENS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROPRIEDADES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTRATOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CAMPANHAS_MARKETING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBROS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USINAS START WITH 1 INCREMENT BY 1;


INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'João Silva', 'joao.silva@email.com', '123456789', SYSDATE, 'Rua A, 123');
INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Maria Oliveira', 'maria.oliveira@email.com', '987654321', SYSDATE, 'Rua B, 456');
INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Carlos Pereira', 'carlos.pereira@email.com', '555333222', SYSDATE, 'Rua C, 789');
INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Ana Souza', 'ana.souza@email.com', '333222111', SYSDATE, 'Rua D, 101');
INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Fernanda Lima', 'fernanda.lima@email.com', '555444333', SYSDATE, 'Rua E, 202');
INSERT INTO CLIENTES (CLIENTE_ID, NOME, EMAIL, TELEFONE, DATA_CADASTRO, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Rafael Costa', 'rafael.costa@email.com', '666777888', SYSDATE, 'Rua F, 303');

-- Inserir dados na tabela CAMPANHAS
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha A', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-02-01', 'YYYY-MM-DD'), 5000.00);
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha B', TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-04-01', 'YYYY-MM-DD'), 7000.00);
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha C', TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-06-01', 'YYYY-MM-DD'), 8000.00);
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha D', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-08-01', 'YYYY-MM-DD'), 6000.00);
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha E', TO_DATE('2024-09-01', 'YYYY-MM-DD'), TO_DATE('2024-10-01', 'YYYY-MM-DD'), 9000.00);
INSERT INTO CAMPANHAS (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS.NEXTVAL, 'Campanha F', TO_DATE('2024-11-01', 'YYYY-MM-DD'), TO_DATE('2024-12-01', 'YYYY-MM-DD'), 10000.00);

INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 1, 1, TO_DATE('2024-01-05', 'YYYY-MM-DD'), 'Email', 'Abertura', 150.00);
INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 2, 1, TO_DATE('2024-01-06', 'YYYY-MM-DD'), 'SMS', 'Clique', 100.00);
INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 3, 2, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 'Email', 'Abertura', 200.00);
INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 4, 2, TO_DATE('2024-03-12', 'YYYY-MM-DD'), 'Webinar', 'Participação', 250.00);
INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 5, 3, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 'Social Media', 'Clique', 120.00);
INSERT INTO INTERACOES (INTERACAO_ID, CLIENTE_ID, CAMPANHA_ID, DATA_INTERACAO, TIPO, METRICA, VALOR)
VALUES (SEQ_INTERACOES.NEXTVAL, 6, 3, TO_DATE('2024-05-20', 'YYYY-MM-DD'), 'Promoção', 'Compra', 180.00);


INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'Carlos Souza', TO_DATE('2000-05-15', 'YYYY-MM-DD'), 'M12345', 1);
INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'Luciana Alves', TO_DATE('2001-08-23', 'YYYY-MM-DD'), 'M23456', 2);
INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'Roberta Martins', TO_DATE('2000-11-02', 'YYYY-MM-DD'), 'M34567', 3);
INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'Felipe Costa', TO_DATE('1999-01-14', 'YYYY-MM-DD'), 'M45678', 4);
INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'Mariana Ribeiro', TO_DATE('2002-06-30', 'YYYY-MM-DD'), 'M56789', 5);
INSERT INTO ESTUDANTES (ESTUDANTE_ID, NOME, DATA_NASCIMENTO, MATRICULA, CURSO_ID)
VALUES (SEQ_ESTUDANTES.NEXTVAL, 'José Pereira', TO_DATE('1999-12-20', 'YYYY-MM-DD'), 'M67890', 6);


INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Paulo Pereira', 'Matemática');
INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Cláudia Almeida', 'Física');
INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Juliana Mendes', 'Química');
INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Carlos Oliveira', 'Informática');
INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Renata Costa', 'Biologia');
INSERT INTO PROFESSORES (PROFESSOR_ID, NOME, DEPARTAMENTO)
VALUES (SEQ_PROFESSORES.NEXTVAL, 'Eduardo Souza', 'História');


INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Engenharia de Software', 'Curso de Desenvolvimento de Software', 5);
INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Medicina', 'Curso de Medicina', 6);
INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Direito', 'Curso de Direito', 5);
INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Arquitetura', 'Curso de Arquitetura', 5);
INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Psicologia', 'Curso de Psicologia', 5);
INSERT INTO CURSOS (CURSO_ID, NOME, DESCRICAO, DURACAO)
VALUES (SEQ_CURSOS.NEXTVAL, 'Administração', 'Curso de Administração', 4);


INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Matemática Discreta', 1, 1);
INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Física 1', 2, 2);
INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Direito Constitucional', 3, 3);
INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Desenho Arquitetônico', 4, 4);
INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Psicologia Clínica', 5, 5);
INSERT INTO DISCIPLINAS (DISCIPLINA_ID, NOME, CURSO_ID, PROFESSOR_ID)
VALUES (SEQ_DISCIPLINAS.NEXTVAL, 'Gestão Empresarial', 6, 6);

INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 1, 1, TO_DATE('2024-01-15', 'YYYY-MM-DD'));
INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 2, 2, TO_DATE('2024-02-10', 'YYYY-MM-DD'));
INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 3, 3, TO_DATE('2024-03-05', 'YYYY-MM-DD'));
INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 4, 4, TO_DATE('2024-04-01', 'YYYY-MM-DD'));
INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 5, 5, TO_DATE('2024-05-20', 'YYYY-MM-DD'));
INSERT INTO MATRICULAS (MATRICULA_ID, ESTUDANTE_ID, DISCIPLINA_ID, DATA_MATRICULA)
VALUES (SEQ_MATRICULAS.NEXTVAL, 6, 6, TO_DATE('2024-06-15', 'YYYY-MM-DD'));


INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Roberto Silva', TO_DATE('1985-03-10', 'YYYY-MM-DD'), 'Gerente', 5000.00, TO_DATE('2015-06-01', 'YYYY-MM-DD'), 1);
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Patricia Costa', TO_DATE('1990-07-20', 'YYYY-MM-DD'), 'Analista', 3500.00, TO_DATE('2018-08-10', 'YYYY-MM-DD'), 2);
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Juliana Martins', TO_DATE('1983-05-14', 'YYYY-MM-DD'), 'Assistente', 3000.00, TO_DATE('2019-02-01', 'YYYY-MM-DD'), 3);
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Carlos Oliveira', TO_DATE('1980-10-10', 'YYYY-MM-DD'), 'Diretor', 8000.00, TO_DATE('2010-03-15', 'YYYY-MM-DD'), 4);
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Fernanda Lima', TO_DATE('1992-12-05', 'YYYY-MM-DD'), 'Supervisor', 4500.00, TO_DATE('2017-04-12', 'YYYY-MM-DD'), 5);
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Eduardo Souza', TO_DATE('1988-02-20', 'YYYY-MM-DD'), 'Coordenador', 5500.00, TO_DATE('2016-07-10', 'YYYY-MM-DD'), 6);


INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto A', 'Desenvolvimento de Sistema A', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 100000.00);
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto B', 'Pesquisa e Desenvolvimento de Produto B', TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-11-30', 'YYYY-MM-DD'), 150000.00);
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto C', 'Expansão de Mercado C', TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD'), 120000.00);
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto D', 'Modernização de Infraestrutura D', TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2025-03-31', 'YYYY-MM-DD'), 200000.00);
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto E', 'Melhoria de Processos E', TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-08-31', 'YYYY-MM-DD'), 80000.00);
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_PROJETOS.NEXTVAL, 'Projeto F', 'Criação de Website F', TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 90000.00);


INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 1, 'Tarefa A1', 'Desenvolvimento do módulo A1', 2, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-02-28', 'YYYY-MM-DD'), 'Em andamento');
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 2, 'Tarefa B1', 'Pesquisa de mercado B1', 3, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-03-15', 'YYYY-MM-DD'), 'Não iniciada');
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 3, 'Tarefa C1', 'Análise de dados C1', 4, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-04-15', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 4, 'Tarefa D1', 'Redesign da infraestrutura D1', 5, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 'Em andamento');
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 5, 'Tarefa E1', 'Otimização de processos E1', 6, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 'Não iniciada');
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (SEQ_TAREFAS.NEXTVAL, 6, 'Tarefa F1', 'Desenvolvimento do website F1', 2, TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD'), 'Em andamento');


INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'ABC1234', 'F4000', 10.5, 'Disponível');
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'XYZ5678', 'Sprinter', 5.0, 'Em uso');
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'LMN9876', 'Van 3000', 3.5, 'Disponível');
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'PQR4567', 'Caminhão', 15.0, 'Em manutenção');
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'STU8765', 'Furgão', 8.0, 'Disponível');
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'VWX4321', 'Vito', 6.0, 'Em uso');


INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'São Paulo', 'Rio de Janeiro', 400.00);
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'São Paulo', 'Belo Horizonte', 600.00);
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Rio de Janeiro', 'Vitória', 550.00);
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Curitiba', 'Florianópolis', 300.00);
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Porto Alegre', 'Santa Maria', 250.00);
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Salvador', 'Aracaju', 200.00);


INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 1, 3, 1, TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 2, 4, 2, TO_DATE('2024-02-20', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Em andamento');
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 3, 5, 3, TO_DATE('2024-03-10', 'YYYY-MM-DD'), TO_DATE('2024-03-10', 'YYYY-MM-DD'), 'Em andamento');
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 4, 6, 4, TO_DATE('2024-04-05', 'YYYY-MM-DD'), TO_DATE('2024-04-05', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 5, 2, 5, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-05-01', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 6, 3, 6, TO_DATE('2024-06-12', 'YYYY-MM-DD'), TO_DATE('2024-06-12', 'YYYY-MM-DD'), 'Em andamento');


INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Rua das Flores, 123', 'Apartamento', 350000.00, 'Disponível');
INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Avenida Central, 456', 'Casa', 500000.00, 'Em venda');
INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Rua dos Coqueiros, 789', 'Comercial', 800000.00, 'Alugada');
INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Rua da Paz, 101', 'Apartamento', 320000.00, 'Disponível');
INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Avenida do Sol, 202', 'Casa', 600000.00, 'Em venda');
INSERT INTO PROPRIEDADES (PROPRIEDADE_ID, ENDERECO, TIPO, PRECO, STATUS)
VALUES (SEQ_PROPRIEDADES.NEXTVAL, 'Rua das Acácias, 303', 'Comercial', 950000.00, 'Alugada');


INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 1, 1, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 1500.00, 'Aluguel');
INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 2, 2, 2, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2025-02-01', 'YYYY-MM-DD'), 2500.00, 'Venda');
INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 3, 3, 3, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-01', 'YYYY-MM-DD'), 3500.00, 'Aluguel');
INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 4, 4, 4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2025-04-01', 'YYYY-MM-DD'), 1800.00, 'Aluguel');
INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 5, 5, 5, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2025-05-01', 'YYYY-MM-DD'), 2300.00, 'Venda');
INSERT INTO CONTRATOS (CONTRATO_ID, PROPRIEDADE_ID, PROPRIETARIO_ID, CLIENTE_ID, DATA_INICIO, DATA_FIM, VALOR_MENSAL, TIPO)
VALUES (SEQ_CONTRATOS.NEXTVAL, 6, 6, 6, TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2025-06-01', 'YYYY-MM-DD'), 2800.00, 'Aluguel');


INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Verão 2024', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-03-31', 'YYYY-MM-DD'), 50000.00);
INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Outono 2024', TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 60000.00);
INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Inverno 2024', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD'), 70000.00);
INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Primavera 2024', TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 80000.00);
INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Black Friday 2024', TO_DATE('2024-11-01', 'YYYY-MM-DD'), TO_DATE('2024-11-30', 'YYYY-MM-DD'), 90000.00);
INSERT INTO CAMPANHAS_MARKETING (CAMPANHA_ID, NOME, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (SEQ_CAMPANHAS_MARKETING.NEXTVAL, 'Campanha Natal 2024', TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2024-12-25', 'YYYY-MM-DD'), 100000.00);


INSERT INTO MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (SEQ_MEMBROS.NEXTVAL, 'João Pereira', TO_DATE('1985-06-10', 'YYYY-MM-DD'), '999999999', 'joao@example.com');
INSERT INTO MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (SEQ_MEMBROS.NEXTVAL, 'Maria Oliveira', TO_DATE('1990-07-15', 'YYYY-MM-DD'), '988888888', 'maria@example.com');
INSERT INTO MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (SEQ_MEMBROS.NEXTVAL, 'Carlos Silva', TO_DATE('1982-11-20', 'YYYY-MM-DD'), '977777777', 'carlos@example.com');
INSERT INTO MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (SEQ_MEMBROS.NEXTVAL, 'Fernanda Costa', TO_DATE('1995-01-25', 'YYYY-MM-DD'), '966666666', 'fernanda@example.com');
INSERT INTO MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (SEQ_MEMBROS.NEXTVAL, 'Ricardo Souza', TO_DATE('1992-05-30', 'YYYY-MM-DD'), '955555555', 'ricardo@example.com');


INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Solar Luz do Sol', 'Solar', 5000.00, 'São Paulo');
INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Hidrelétrica Xingu', 'Hidrelétrica', 20000.00, 'Amazonas');
INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Eólica Ventos do Sertão', 'Eólica', 1500.00, 'Ceará');
INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Termelétrica Fogo Azul', 'Termelétrica', 10000.00, 'Rio de Janeiro');
INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Nuclear Atômica', 'Nuclear', 30000.00, 'Minas Gerais');
INSERT INTO USINAS (USINA_ID, NOME, TIPO, CAPACIDADE_GERACAO, LOCALIZACAO)
VALUES (SEQ_USINAS.NEXTVAL, 'Usina Solar Sertão Verde', 'Solar', 8000.00, 'Pernambuco');