CREATE TABLE CURSOS (
    CURSO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO NUMBER,
    CONSTRAINT PK_CURSOS PRIMARY KEY (CURSO_ID)
);

CREATE TABLE CLIENTES (
    CLIENTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    TELEFONE VARCHAR2(15),
    DATA_CADASTRO DATE,
    ENDERECO VARCHAR2(255),
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTE_ID)
);

CREATE TABLE CAMPANHAS (
    CAMPANHA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ORCAMENTO NUMBER(10, 2),
    CONSTRAINT PK_CAMPANHAS PRIMARY KEY (CAMPANHA_ID)
);

CREATE TABLE PROFESSORES (
    PROFESSOR_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(100),
    CONSTRAINT PK_PROFESSORES PRIMARY KEY (PROFESSOR_ID)
);

CREATE TABLE DISCIPLINAS (
    DISCIPLINA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CURSO_ID NUMBER,
    PROFESSOR_ID NUMBER,
    CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (DISCIPLINA_ID),
    CONSTRAINT FK_DISCIPLINAS_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS (CURSO_ID),
    CONSTRAINT FK_DISCIPLINAS_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORES (PROFESSOR_ID)
);

CREATE TABLE ESTUDANTES (
    ESTUDANTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    MATRICULA VARCHAR2(20),
    CURSO_ID NUMBER,
    CONSTRAINT PK_ESTUDANTES PRIMARY KEY (ESTUDANTE_ID),
    CONSTRAINT FK_ESTUDANTES_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS (CURSO_ID)
);

CREATE TABLE MATRICULAS (
    MATRICULA_ID NUMBER NOT NULL,
    ESTUDANTE_ID NUMBER NOT NULL,
    DISCIPLINA_ID NUMBER NOT NULL,
    DATA_MATRICULA DATE,
    CONSTRAINT PK_MATRICULAS PRIMARY KEY (MATRICULA_ID),
    CONSTRAINT FK_MATRICULAS_ESTUDANTE FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTES (ESTUDANTE_ID),
    CONSTRAINT FK_MATRICULAS_DISCIPLINA FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINAS (DISCIPLINA_ID)
);

CREATE TABLE INTERACOES (
    INTERACAO_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    CAMPANHA_ID NUMBER NOT NULL,
    DATA_INTERACAO DATE,
    TIPO VARCHAR2(50),
    METRICA VARCHAR2(100),
    VALOR NUMBER,
    CONSTRAINT PK_INTERACOES PRIMARY KEY (INTERACAO_ID),
    CONSTRAINT FK_INTERACOES_CLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID),
    CONSTRAINT FK_INTERACOES_CAMPANHAS FOREIGN KEY (CAMPANHA_ID) REFERENCES CAMPANHAS (CAMPANHA_ID)
);

CREATE TABLE FUNCIONARIOS (
    FUNCIONARIO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    CARGO VARCHAR2(50),
    SALARIO NUMBER(10, 2),
    DATA_ADMISSAO DATE,
    DEPARTAMENTO_ID NUMBER,
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (FUNCIONARIO_ID)
);

CREATE TABLE PROJETOS (
    PROJETO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ORCAMENTO NUMBER(10, 2),
    CONSTRAINT PK_PROJETOS PRIMARY KEY (PROJETO_ID)
);

CREATE TABLE TAREFAS (
    TAREFA_ID NUMBER NOT NULL,
    PROJETO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    RESPONSAVEL_ID NUMBER,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT PK_TAREFAS PRIMARY KEY (TAREFA_ID),
    CONSTRAINT FK_TAREFAS_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETOS (PROJETO_ID)
);

CREATE TABLE VEICULOS (
    VEICULO_ID NUMBER NOT NULL,
    PLACA VARCHAR2(10) NOT NULL,
    MODELO VARCHAR2(100),
    CAPACIDADE_CARGA NUMBER(10, 2),
    STATUS VARCHAR2(50),
    CONSTRAINT PK_VEICULOS PRIMARY KEY (VEICULO_ID)
);

CREATE TABLE ROTAS (
    ROTA_ID NUMBER NOT NULL,
    ORIGEM VARCHAR2(100) NOT NULL,
    DESTINO VARCHAR2(100) NOT NULL,
    DISTANCIA NUMBER(10, 2),
    CONSTRAINT PK_ROTAS PRIMARY KEY (ROTA_ID)
);

CREATE TABLE VIAGENS (
    VIAGEM_ID NUMBER NOT NULL,
    VEICULO_ID NUMBER NOT NULL,
    MOTORISTA_ID NUMBER NOT NULL,
    ROTA_ID NUMBER,
    DATA_PARTIDA DATE,
    DATA_CHEGADA DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT PK_VIAGENS PRIMARY KEY (VIAGEM_ID),
    CONSTRAINT FK_VIAGENS_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES VEICULOS (VEICULO_ID),
    CONSTRAINT FK_VIAGENS_ROTA FOREIGN KEY (ROTA_ID) REFERENCES ROTAS (ROTA_ID)
);

CREATE TABLE PROPRIEDADES (
    PROPRIEDADE_ID NUMBER NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TIPO VARCHAR2(50),
    PRECO NUMBER(15, 2),
    STATUS VARCHAR2(50),
    CONSTRAINT PK_PROPRIEDADES PRIMARY KEY (PROPRIEDADE_ID)
);

CREATE TABLE CONTRATOS (
    CONTRATO_ID NUMBER NOT NULL,
    PROPRIEDADE_ID NUMBER NOT NULL,
    PROPRIETARIO_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    VALOR_MENSAL NUMBER(10, 2),
    TIPO VARCHAR2(50),
    CONSTRAINT PK_CONTRATOS PRIMARY KEY (CONTRATO_ID),
    CONSTRAINT FK_CONTRATOS_PROPRIEDADES FOREIGN KEY (PROPRIEDADE_ID) REFERENCES PROPRIEDADES (PROPRIEDADE_ID)
);

CREATE TABLE CAMPANHAS_MARKETING (
    CAMPANHA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ORCAMENTO NUMBER(10, 2),
    CONSTRAINT PK_CAMPANHAS_MARKETING PRIMARY KEY (CAMPANHA_ID)
);

CREATE TABLE MEMBROS (
    MEMBRO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CONSTRAINT PK_MEMBROS PRIMARY KEY (MEMBRO_ID)
);

CREATE TABLE USINAS (
    USINA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    CAPACIDADE_GERACAO NUMBER(10,2),
    LOCALIZACAO VARCHAR2(100),
    CONSTRAINT PK_USINAS PRIMARY KEY (USINA_ID)
);

